services:
  mysqldb:
      image: mysql:latest
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQLDB_PASSWORD}
      ports:
        - 3307:3306
      command: --init-file /data/application/schemaExample.sql
      volumes:
        - ./schemaExample.sql:/data/application/schemaExample.sql
      networks:
        - app-network
      restart: always
  app:
    build: .
    ports:
      - 8800:8800
    depends_on:
      - mysqldb
    volumes:
      - ./uploads:/app/uploads
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
